---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-microservice
spec:
  selector:
    matchLabels:
      app: rating-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rating-app
    spec:
      containers:
        - name: rating-microservice-k8s
          image: 471112969494.dkr.ecr.us-east-1.amazonaws.com/employee:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rating-microservice-svc
spec:
  selector:
    app: rating-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer